"""Labours

Revision ID: 637943f2f189
Revises: a53e6ade5fde
Create Date: 2020-10-13 19:58:06.706308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637943f2f189'
down_revision = 'a53e6ade5fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('perfomance_time', sa.Interval(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labour_to_problem',
    sa.Column('labour', sa.Integer(), nullable=True),
    sa.Column('problem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labour'], ['labours.id'], ),
    sa.ForeignKeyConstraint(['problem'], ['problems.id'], )
    )
    op.create_table('user_to_labour',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('labour_id', sa.Integer(), nullable=False),
    sa.Column('performance_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['labour_id'], ['labours.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'labour_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_labour')
    op.drop_table('labour_to_problem')
    op.drop_table('labours')
    # ### end Alembic commands ###
