"""Created news rating and UserToNews association

Revision ID: 847c2db2d27b
Revises: c2ec566a378f
Create Date: 2020-10-02 08:03:39.066386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847c2db2d27b'
down_revision = 'c2ec566a378f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'rating')
    # ### end Alembic commands ###
