"""Created userpic URI

Revision ID: 9f7da1dbf4df
Revises: 847c2db2d27b
Create Date: 2020-10-03 08:21:53.553560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7da1dbf4df'
down_revision = '847c2db2d27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userpic_uri', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userpic_uri')
    # ### end Alembic commands ###
