"""Integering submission verdict

Revision ID: a53e6ade5fde
Revises: 9f7da1dbf4df
Create Date: 2020-10-06 16:08:06.535676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53e6ade5fde'
down_revision = '9f7da1dbf4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submissions") as batch_op:
        batch_op.alter_column('verdict',
                   existing_type=sa.VARCHAR(),
                    type_=sa.Integer(),
                    default=0,
                   nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'verdict',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
