"""Labour duration to end date

Revision ID: ae82612dc3c1
Revises: 637943f2f189
Create Date: 2020-11-11 16:05:20.085327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae82612dc3c1'
down_revision = '637943f2f189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labours', sa.Column('end_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table("labours") as batch_op:
        batch_op.drop_column('labours', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labours', sa.Column('duration', sa.DATETIME(), nullable=True))
    op.drop_column('labours', 'end_date')
    # ### end Alembic commands ###
