"""Deleted test number

Revision ID: c2ec566a378f
Revises: 
Create Date: 2020-10-01 16:30:11.733368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ec566a378f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    naming_convention = {
        "fk":
        "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"
    }
    
    with op.batch_alter_table("submissions",
                              naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint("fk_submissions_test_tests", type_="foreignkey")

    
    with op.batch_alter_table("tests") as batch_op:
        batch_op.drop_column('number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('number', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'submissions', 'tests', ['test'], ['number'])
    # ### end Alembic commands ###
